#ifndef __HTTPS_CERTS_H__
#define __HTTPS_CERTS_H__


#ifdef __cplusplus
extern "C" {
#endif


#define CA "-----BEGIN CERTIFICATE-----\n\
MIICMjCCAZsCFHMjvWC81J7fAQNb2RjEZlb86Z+lMA0GCSqGSIb3DQEBCwUAMFgx\n\
CzAJBgNVBAYTAkJZMREwDwYDVQQIDAhWaXRlYnNrYTEQMA4GA1UEBwwHUG9sb3Rz\n\
azENMAsGA1UECgwEaG9tZTEVMBMGA1UEAwwMMTkyLjE2OC4xLjExMB4XDTIyMTAx\n\
MjEyMDYyMFoXDTMyMTAwOTEyMDYyMFowWDELMAkGA1UEBhMCQlkxETAPBgNVBAgM\n\
CFZpdGVic2thMRAwDgYDVQQHDAdQb2xvdHNrMQ0wCwYDVQQKDARob21lMRUwEwYD\n\
VQQDDAwxOTIuMTY4LjEuMTEwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAOmr\n\
jPjU8Up2FuPreEPokb7O3ZwaMzswX8w2yHBRnuNCn/mM6ZLglKXS/pVvRN0IIqrX\n\
lXBNWk3DMqzuPiIlu+LP/StKv2aUUVB+d9LCvtMzxRuZd+q/0mVtlY3ygs0a8Kzq\n\
AlqqWH4deGjrLF9D7WomChOWTNNe1KHPyewQ9fJ7AgMBAAEwDQYJKoZIhvcNAQEL\n\
BQADgYEAd1XS/Elouhw1vUSrNIhcArqg5ST+Q35I5EnhI/h6B91EORbXqn+mVZmP\n\
Gd4GYOMPKrRRrvGTc73neHdatuJkDN79KladTVvBuKNunQywqGiQGOJ/tWCrAjG8\n\
c28ot7U5V/6oYeoZzicr9sFlvNkzcqoPvKsIY8ey4vl2Hiyjneg=\n\
-----END CERTIFICATE-----"

#define CRT "-----BEGIN CERTIFICATE-----\n\
MIICHDCCAYUCAQIwDQYJKoZIhvcNAQELBQAwWDELMAkGA1UEBhMCQlkxETAPBgNV\n\
BAgMCFZpdGVic2thMRAwDgYDVQQHDAdQb2xvdHNrMQ0wCwYDVQQKDARob21lMRUw\n\
EwYDVQQDDAwxOTIuMTY4LjEuMTEwHhcNMjIxMDEyMTIwNjIwWhcNMzIxMDA5MTIw\n\
NjIwWjBVMQswCQYDVQQGEwJERTELMAkGA1UECAwCQkUxDzANBgNVBAcMBkJlcmxp\n\
bjESMBAGA1UECgwJTXlDb21wYW55MRQwEgYDVQQDDAtlc3AzMi5sb2NhbDCBnzAN\n\
BgkqhkiG9w0BAQEFAAOBjQAwgYkCgYEAu4lbHMRDmZmPNviqQWrDVNYFXXYX8/sm\n\
VwCwbz+OBSDeIE17TcXj6naA1P9ACBKy/lRwyTZd2NcNW9WsoYVBOO/9eYCQSOYw\n\
yLDCB0dO0SO6/NC5RLN9C7fNBZi+5mTdDW68oRADoXq+rKFWVUI6Qs8nCmG+7rh8\n\
55uvVSnYPqECAwEAATANBgkqhkiG9w0BAQsFAAOBgQBfzCa5imhDXY/bEQeFYwK+\n\
Mp4NkKV4xU+lPhpNstVGtn0VRh8deomVoa+J3Yo/XQYPBCRKiIsKo0/mysm9BsFJ\n\
OzPSumXSEaIQomxNNpqaeUpNKvdMy0l0HdL0HTwxqStXNXSdNt97pW1JmbvxuN+O\n\
s/z+wYjAvQYlsjMd+qNtDw==\n\
-----END CERTIFICATE-----"

#define KEY "-----BEGIN RSA PRIVATE KEY-----\n\
MIICXAIBAAKBgQC7iVscxEOZmY82+KpBasNU1gVddhfz+yZXALBvP44FIN4gTXtN\n\
xePqdoDU/0AIErL+VHDJNl3Y1w1b1ayhhUE47/15gJBI5jDIsMIHR07RI7r80LlE\n\
s30Lt80FmL7mZN0NbryhEAOher6soVZVQjpCzycKYb7uuHznm69VKdg+oQIDAQAB\n\
AoGBAJjMKC0/B+kdQZ/DaUzVhQMZQdPNhWSnq6xVhmuN99Pb3L+rAZzzcGi3Vu60\n\
beJmAerQt/hpUHt9dIfvh7Eull07g8J0aGKOE+qPI04MKJb/ErxO2A9E+XXvFuHj\n\
4/gpssMWwNDNUGj4TVbJneekBa4MAGGENhF+IITJ+Q+0zg3BAkEA9NUcYK4lWLgs\n\
kSf97ymcxnKCsiotCE0ZAO7eW/Ca5Ow1B3iTsKSoxFsjkrctWzwL5cG6ULnmZ9gP\n\
gE33r3NjWQJBAMQXNIfVaQY2dc1yl9UyOZ2g3gZHat+Kxq+TmjSTIh84rwzexT31\n\
aiHNmAyNUyC715peoIanbjFFJpsoelD6NIkCQEV+QAHJLFyUWkIRYeiCnTdOxX4g\n\
rouOpqw3IPJjxvN3gE3Qkcsv0Z96Zwx75enhj1b1uBa1zYpoL24xsz4fuHECQB+g\n\
Rn6p8thnrDRIiSh/gz9jFKwalKgdL9Jdkf9sw5IZiFIhE9rcXBO7nwxXNtMOuMVT\n\
Abz2ABW+O23G54Nr91ECQGly181Han5wYBGqDJ6KFsnRg3VXLnB/m69WWt/K9xDs\n\
4zeN4EQUdCe3gSGQIkdUDwugyEXSWK+DulMBlDvzHQk=\n\
-----END RSA PRIVATE KEY-----"

#ifdef __cplusplus
}
#endif

#endif /* __HTTPS_CERTS_H__ */