---
components:
  - name: lampwm
    description: |
      Driver for control LED lamp
    group:
      name: lampwm
    groups:
      - name: lampwm
    code_owners:
      - name: Vivask
    depends:
      - name: log
    thread_safe: yes
    targets:
      - name: esp32
    licenses:
      - name: MIT
    copyrights:
      - name: Vivask
        year: 2022
