package proxy

import (
	"fmt"
	"io"
	"os"
)

func (p *Proxy) configLocalResolver() error {
	if len(p.config.LocalResolvers) == 0 {
		return fmt.Errorf("undefined local resolver")
	}

	const fName = "/etc/resolv.conf"
	file, err := os.OpenFile(fName, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0644)
	if err != nil {
		return fmt.Errorf("can't open file: %s, error: %w", fName, err)
	}
	defer file.Close()

	io.WriteString(file, "#Generated by meteo daemon\n")

	for _, resolver := range p.config.LocalResolvers {
		nameserver := fmt.Sprintf("nameserver %s\n", resolver)
		io.WriteString(file, nameserver)
	}

	return nil
}
