#!/bin/bash

meteodir='/home/alarm/Projects/Meteo.esp32'
godir='/home/alarm/Projects/Meteo.esp32/other/meteo-daemon'
curdir=`pwd`

rm -f meteo-daemon
cd $meteodir
git pull
cd $godir
go build main.go
mv ./main ./meteo-daemon
chown -R git:git $godir
chown -R git:git /opt/www/git/Mikrotik
chown -R git:git /var/log/meteo-daemon
systemctl restart meteo-daemon
cd $curdir
